version: '3.9'

networks:
  localdev:
    name: localdev

services:
  tweet-api:
    build: .
    container_name: tweet-api-instance
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - localdev
  
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - localdev